'use strict';
/**
 * OpenVibe.Live's AI features as workflows, moved from Live with minimal change.
 *
 * Two shapes:
 *   - STRUCTURED workflows own their prompt here (versioned templates) and take structured input:
 *     translation, paste image/text analysis, stream-frame description (moments), stream summary
 *     (stream memory / overview + inferred category), streamer overview, VOD/clip media overview,
 *     stream recap, speech-to-text, and Network's footer copy (the dependency the plan reverses).
 *   - PASSTHROUGH workflows carry a prompt Live still renders itself (chat AI viewers, chat
 *     insights, moment ranking, slogans, easter eggs, arena, home star …). Each Live feature has
 *     its own workflow key so every run stays attributable to a workflow + model + run (§33);
 *     their prompts move into templates feature by feature (docs/migration.md).
 *
 * Prompt text below is copied verbatim from Live (server/i18n/translate.js, server/ai/ai-analysis.js,
 * server/ai/media-analysis.js, server/recap/recap.js, server/internal/routes.js).
 */
const { IMAGE, MEDIA_REF, SOURCES } = require('./common-schemas');

const ROLES = ['chat', 'vision', 'director', 'summary', 'legacy'];
const LANG = { type: 'string', pattern: '^(auto|[a-z]{2})$' };
const STR = (n) => ({ type: 'string', maxLength: n });

// ── Templates ────────────────────────────────────────────
const templates = [
    {
        key: 'live.translate', name: 'Live: translate chat, bio or speech',
        description: 'From server/i18n/translate.js. Keeps tone, slang, emotes and mentions; speech keeps line count.',
        input_schema: { type: 'object' }, output_schema: { type: 'object' },
        system_prompt: 'You translate {{kind}} from {{src}} to {{dst}}. Rules: keep the tone, slang, jokes, profanity and emoji as they are; keep names, URLs, :emotes:, !commands and @mentions unchanged; never add explanations, notes, quotes or brackets; if it is already in the target language, return it unchanged.{{#speech}} Input may contain several lines separated by newlines — return exactly the same number of lines, in order.{{/speech}} Output ONLY the translation.',
        user_prompt: '{{text}}',
        default_route: 'live.chat', owner: 'live',
    },
    {
        key: 'live.paste.describe_image', name: 'Live: describe an image paste or moment frame',
        description: 'From ai-analysis.analyzeImagePaste (paste_image, moment_frame).',
        input_schema: { type: 'object' }, output_schema: { type: 'object' },
        system_prompt: '',
        user_prompt: 'You are describing an uploaded image/screenshot for a paste titled "{{title}}".\nReply ONLY with compact JSON: {"description":"1-2 sentence description of what the image shows","tags":["3-6","short","lowercase","tags"]}.',
        default_route: 'live.vision', owner: 'live',
    },
    {
        key: 'live.paste.summarize_text', name: 'Live: summarize a text paste',
        description: 'From ai-analysis.analyzeTextPaste (paste_text).',
        input_schema: { type: 'object' }, output_schema: { type: 'object' },
        system_prompt: '',
        user_prompt: 'Summarize what this pasted text is about in one short sentence (max 200 chars), plainly. Title: "{{title}}".\n\n---\n{{snippet}}',
        default_route: 'live.legacy', owner: 'live',
    },
    {
        key: 'live.stream.describe_frame', name: 'Live: describe a live-stream frame',
        description: 'From ai-analysis.analyzeStreamFrame (stream_memory): memory description, tags, and a screenshot-worthiness verdict + caption for live pastes, in one vision call.',
        input_schema: { type: 'object' }, output_schema: { type: 'object' },
        system_prompt: '',
        user_prompt: 'This is a frame from a live stream. Reply ONLY with compact JSON: {"description":"one concise sentence describing what is happening on screen right now","tags":["2-5","short","tags"],"worthy":<true only if this exact frame is genuinely screenshot-worthy on its own: a face/reaction, a visual gag, something unusual or funny on screen — false for ordinary gameplay/desktop/chat/talking-head frames>,"title":"<if worthy: a punchy, funny 3-7 word caption for it, else empty>"}.',
        default_route: 'live.vision', owner: 'live',
    },
    {
        key: 'live.stream.summarize', name: 'Live: stream overview + inferred category',
        description: 'From ai-analysis.summarizeStreamMemories: whole-session overview from timestamped observations and the audio timeline; category is inferred, never defaulted.',
        input_schema: { type: 'object' }, output_schema: { type: 'object' },
        system_prompt: '',
        user_prompt: 'These are timestamped observations from a live stream, in order since it started. Reply ONLY with compact JSON: {"overview":"a thorough overview (2-6 sentences) of what this stream has been about overall — the main activities, topics, and vibe across the whole session (not just the latest moment)","category":"<exactly one of: {{categories}} — what this stream mostly IS, judged from the observations; desktop = screen/software/coding, gaming = playing games, irl = camera on a person talking/doing things indoors, outdoors/travel = out in the world>","tags":["3-6","short","lowercase","tags"]}\n{{lines}}{{audio_block}}',
        default_route: 'live.legacy', owner: 'live',
    },
    {
        key: 'live.streamer.overview', name: 'Live: internal streamer profile for staff',
        description: 'From ai-analysis.generateStreamerOverview.',
        input_schema: { type: 'object' }, output_schema: { type: 'object' },
        system_prompt: '',
        user_prompt: 'You are building an internal profile of a livestreamer for site staff, using aggregated signals across their streams, VODs, and pastes. Write a concise overview (4-8 sentences) covering: what they stream / their content niche, recurring themes or activities, tone/vibe, and anything notable for moderation. Be factual and neutral; do NOT invent specifics that aren\'t supported by the signals below.\n\n{{ctx}}',
        default_route: 'live.legacy', owner: 'live',
    },
    {
        key: 'live.media.overview', name: 'Live: VOD/clip overview from frames + transcript',
        description: 'From media-analysis.analyzeMedia (media_overview).',
        input_schema: { type: 'object' }, output_schema: { type: 'object' },
        system_prompt: '',
        user_prompt: 'You are writing an AI overview of a recorded video. Using ONLY the signals below (be concrete, don\'t invent), summarize what the video is about in 2-5 sentences — the main activities, topics, and vibe.\n\n{{parts}}',
        default_route: 'live.legacy', owner: 'live',
    },
    {
        key: 'live.viewers.plan', name: "Live: AI viewers director",
        description: "From viewers/director.js plan() (ai_viewers_director): the rules in the system prompt, then the stream's stable context (both cached); the volatile tail is the user message.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "properties": {"skip": {"type": "boolean", "description": "true when nothing worth saying right now"}, "notes": {"type": "string", "description": "one short line of director reasoning (logged only)"}, "lines": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"bot": {"type": "string", "description": "username of the AI viewer that speaks"}, "target": {"type": "string", "enum": ["viewer", "bot", "streamer", "ambient"]}, "reply_to": {"type": ["string", "null"], "description": "username being replied to (viewer or bot), else null"}, "thread": {"type": ["string", "null"], "description": "existing thread id as a string, \"new\" to start one, or null"}, "topic": {"type": ["string", "null"], "description": "topic label when thread is \"new\""}, "delay_ms": {"type": "integer", "minimum": 0, "maximum": 45000}, "text": {"type": "string", "description": "the chat line, in character"}, "reason": {"type": "string", "description": "why this bot says this now (<= 80 chars)"}}, "required": ["bot", "target", "reply_to", "thread", "topic", "delay_ms", "text", "reason"]}}, "threads_close": {"type": "array", "items": {"type": "string"}, "description": "thread ids that reached a natural end"}}, "required": ["skip", "notes", "lines", "threads_close"]},
        system_prompt: "You are the DIRECTOR of a cast of AI viewers in a live stream's chat. Each pass you decide which of them speak next, to whom, and what they say — like an improv coach cueing actors. You never speak yourself.\n\nHard rules:\n- Every line must sound like a real, casual chat message from that specific viewer, fully in character and in their typing style. Short. No quotation marks, no stage directions, no meta commentary, never mention being an AI, bot, model, or \"director\".\n- If the streamer addressed chat or named an AI viewer, that MUST be answered first (target \"streamer\"), naturally and specifically about what they said/are doing.\n- Reply to real viewers when it makes sense (target \"viewer\", reply_to = their username). Prefer people flagged first-time / follower / subscriber. Never reply to yourself.\n- Bots may talk to each other (target \"bot\", reply_to = the other bot) to continue an open thread or start one when chat is quiet — keep the bot-to-bot share at or under the target given, and keep each thread moving (a question, a joke callback, a disagreement), then let it end.\n- \"ambient\" lines react to what is happening on stream (heard / seen) — not filler like \"nice stream\".\n- Use the transcript and screen description as the source of truth for what is happening; the timestamps tell you what is recent.\n- Vary who speaks; the same viewer never posts two lines in a row; spread delay_ms so lines arrive over the pass, streamer replies first (small delay).\n- Respect the channel rules, tone, language, blocklist and the word limit. Plain text only; emoji only per the emote policy.\n- Do not repeat anything already said in chat, by anyone. If there is genuinely nothing to add, return skip=true with an empty lines array.\n\n{{stable}}",
        user_prompt: "{{volatile}}\n\nPlan the next pass now (at most {{max_lines}} lines). Return JSON only.",
        default_route: 'live.director', owner: 'live', metadata: { json_name: 'plan' },
    },
    {
        key: 'live.viewers.reply', name: "Live: AI viewer fast reply to the streamer",
        description: "From viewers/director.js quickReply() (ai_viewers_reply): one line from one viewer answering the streamer.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["text"], "properties": {"text": {"type": "string"}}},
        system_prompt: "You are the DIRECTOR of a cast of AI viewers in a live stream's chat. Each pass you decide which of them speak next, to whom, and what they say — like an improv coach cueing actors. You never speak yourself.\n\nHard rules:\n- Every line must sound like a real, casual chat message from that specific viewer, fully in character and in their typing style. Short. No quotation marks, no stage directions, no meta commentary, never mention being an AI, bot, model, or \"director\".\n- If the streamer addressed chat or named an AI viewer, that MUST be answered first (target \"streamer\"), naturally and specifically about what they said/are doing.\n- Reply to real viewers when it makes sense (target \"viewer\", reply_to = their username). Prefer people flagged first-time / follower / subscriber. Never reply to yourself.\n- Bots may talk to each other (target \"bot\", reply_to = the other bot) to continue an open thread or start one when chat is quiet — keep the bot-to-bot share at or under the target given, and keep each thread moving (a question, a joke callback, a disagreement), then let it end.\n- \"ambient\" lines react to what is happening on stream (heard / seen) — not filler like \"nice stream\".\n- Use the transcript and screen description as the source of truth for what is happening; the timestamps tell you what is recent.\n- Vary who speaks; the same viewer never posts two lines in a row; spread delay_ms so lines arrive over the pass, streamer replies first (small delay).\n- Respect the channel rules, tone, language, blocklist and the word limit. Plain text only; emoji only per the emote policy.\n- Do not repeat anything already said in chat, by anyone. If there is genuinely nothing to add, return skip=true with an empty lines array.\n\n{{stable}}",
        user_prompt: "{{situation}}\n\nThe streamer just said: \"{{streamer_line}}\"\n\nWrite ONE chat line as {{bot}} answering the streamer directly and specifically (max {{max_words}} words, plain text, in character). Return only the line.",
        default_route: 'live.chat', owner: 'live', metadata: {},
    },
    {
        key: 'live.viewers.fold', name: "Live: AI viewers memory fold",
        description: "From viewers/fold.js (ai_viewers_fold): every viewer's recent lines folded into its memory, plus the channel's running bits.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "properties": {"memories": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"bot": {"type": "string"}, "memory": {"type": "string"}}, "required": ["bot", "memory"]}}, "channel_memory": {"type": "string", "description": "running jokes / recurring topics for the whole channel, <= 90 words"}}, "required": ["memories", "channel_memory"]},
        system_prompt: "",
        user_prompt: "You maintain the memories of AI chat personas for one streaming channel.{{#channel_memory}}\n\nCurrent channel memory (running bits): {{channel_memory}}{{/channel_memory}}\n\n{{personas}}\n\nFor each persona, write an updated memory: a tight paragraph (max 90 words) of durable facts — running jokes, who they talk to, opinions they formed, recurring topics. Keep the useful old stuff, drop the trivial. Also update the channel memory (running bits everyone shares).",
        default_route: 'live.summary', owner: 'live', metadata: { json_name: 'fold' },
    },
    {
        key: 'live.viewers.clone', name: "Live: AI viewer cloned from a real chatter",
        description: "From viewers/roster.js createCloneBot (ai_viewers): a character brief from what we know about a real viewer.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["text"], "properties": {"text": {"type": "string"}}},
        system_prompt: "",
        user_prompt: "You are profiling a chat viewer named \"{{name}}\" so an AI can role-play as them.{{#overview}}\n\nWhat we know about them: {{overview}}{{/overview}}{{#memory}}\n\nNotable memory: {{memory}}{{/memory}}{{#samples}}\n\nSample messages they've sent:\n{{samples}}{{/samples}}\n\nWrite a tight 2-3 sentence character brief capturing their vibe, interests, and how they type (tone, casing, slang, length). Second person (\"You are ...\"). No preamble.",
        default_route: 'live.chat', owner: 'live', metadata: {},
    },
    {
        key: 'live.arena.persona', name: "Live: an Arena fighter persona",
        description: "From arena/arena-service.js generatePersona (arena_persona): the character-select bio, voice first, from what they said on stream.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["fighter_name", "title", "class", "element", "signature_move", "special", "weakness", "taunt", "taunts", "typing_style", "spoken_as", "custom_stats", "lore", "catchphrase", "entrance_music", "stat_quips"], "properties": {"fighter_name": {"type": "string", "description": "Arena ring name, 2–5 words, based on the streamer"}, "title": {"type": "string", "description": "Epithet like \"The Midnight Menace of Cozy Corner\""}, "class": {"type": "string", "description": "Fighting-game archetype, e.g. Grappler, Zoner, Rushdown, Summoner, Bard, Tank"}, "element": {"type": "string", "description": "Single word element/vibe"}, "signature_move": {"type": "object", "additionalProperties": false, "required": ["name", "description"], "properties": {"name": {"type": "string"}, "description": {"type": "string"}}}, "special": {"type": "object", "additionalProperties": false, "required": ["name", "description"], "properties": {"name": {"type": "string"}, "description": {"type": "string"}}}, "weakness": {"type": "string"}, "taunt": {"type": "string", "description": "Their signature ragebait line: one sentence, written EXACTLY the way this person types/talks (their punctuation, caps, slang, emoji habits, typos), aimed at rivals or their chat, designed to make people reply"}, "taunts": {"type": "array", "minItems": 3, "maxItems": 3, "items": {"type": "string"}, "description": "three more ragebait/troll lines in their own voice: one at a specific rival from the roster, one at their own chat, one about a topic they will not shut up about"}, "typing_style": {"type": "string", "description": "≤ 12 words describing how they TALK on mic (e.g. \"mumbles, calls everyone bud, yells at chat every 30 seconds\")"}, "custom_stats": {"type": "array", "minItems": 6, "maxItems": 6, "items": {"type": "object", "additionalProperties": false, "required": ["name", "value", "quip"], "properties": {"name": {"type": "string", "description": "≤ 14 chars, a stat that only makes sense for THIS person — named after their actual bits, habits, subjects, gear, rivals, the way they talk (e.g. \"Alt Accounts\", \"Tent Smell\", \"Baby Voice\", \"Reads Chat\", \"Cope\")"}, "value": {"type": "integer", "minimum": 1, "maximum": 99}, "quip": {"type": "string", "description": "≤ 8 words, in their own speaking voice"}}}, "description": "six CHARACTERISTICS unique to this streamer for their radar — read from what they SAY ON MIC (things_they_said_on_stream, their_best_shit_talk, who_they_call_out, what_they_rant_at) and their channel (ai_overview, what the camera saw): the bits they run, what they will not shut up about, how they treat chat, their rivals, their gear obsession, their schedule. Names must be specific to THEM (never generic like \"Hype\" or \"Skill\"), funny, ragebait-ish; values honestly spread (at least one under 30, at least one over 85) and the quip explains the number in their voice."}, "spoken_as": {"type": "array", "minItems": 2, "maxItems": 6, "items": {"type": "string"}, "description": "how OTHER people say or mishear this streamer's name out loud, as a speech-to-text engine would write it: nicknames, shortenings, phonetic misspellings, the handle split into words (e.g. \"japanese old guy\", \"matticus\", \"goose lee\", \"dan\") — lowercase"}, "lore": {"type": "string", "description": "2–3 sentence character-select bio"}, "catchphrase": {"type": "string"}, "entrance_music": {"type": "string"}, "stat_quips": {"type": "object", "additionalProperties": false, "required": ["heat", "aim", "kills", "mouth", "clapback", "stamina", "pace"], "properties": {"heat": {"type": "string", "description": "≤ 8 words explaining their heat rating in character"}, "aim": {"type": "string", "description": "≤ 8 words explaining their aim rating in character"}, "kills": {"type": "string", "description": "≤ 8 words explaining their kills rating in character"}, "mouth": {"type": "string", "description": "≤ 8 words explaining their mouth rating in character"}, "clapback": {"type": "string", "description": "≤ 8 words explaining their clapback rating in character"}, "stamina": {"type": "string", "description": "≤ 8 words explaining their stamina rating in character"}, "pace": {"type": "string", "description": "≤ 8 words explaining their pace rating in character"}}}}},
        system_prompt: "You write fighting-game \"character select\" bios for a live-streaming site's Arena — a battle-cam where streamers talk shit about each other ON MIC and the mic is the only thing that counts. Be savage, profane, petty and funny — roast their habits, their chat, their schedule, their takes, their gimmicks, the way they talk. Trolling energy is welcome; make it quotable.\nVOICE COMES FIRST, AND IT COMES FROM WHAT THEY SAY. The PRIMARY sources are `things_they_said_on_stream` (verbatim speech-to-text, newest first — expect noise), `their_best_shit_talk` (their judged spiciest lines, with who they were aimed at), `who_they_call_out`, `who_calls_them_out`, `what_they_rant_at` and `quotes`. Their streaming profile (`ai_overview`, titles, what the camera saw) is SECONDARY flavor. Copy how they actually talk: their rhythm, pet phrases, how they address chat, how they curse, whether they mumble or yell, sentence length. A taunt must read like something THEY would actually say into the mic — not a movie trailer, not a wrestling promo, no invented catchphrases, never repeat a word for effect, no \"watch me\"/\"try to keep up\" filler.\nTAUNTS ARE THE MOST IMPORTANT PART. They must be RAGEBAIT in that voice: provocative, trolly, specific, petty — the kind of line that makes a rival pull up on stream or a chat reply instantly. Reference their real recurring subjects, rivals from the roster, the people they keep calling out and their obsessions. stat_quips are ALSO in their voice (≤ 8 words each, how THEY would describe that stat). If there is almost no transcript data, infer the voice from the overview and say so in typing_style.\nThis platform does not censor language — offensive and taboo words are allowed. The only hard line: no direct threats of violence, nothing sexual about minors, no doxxing. Everything is Arena lore, not real-life claims. Output only the JSON.",
        user_prompt: "Write the Arena persona for this fighter. Facts (JSON):\n{{json facts}}",
        default_route: 'live.summary', owner: 'live', metadata: { json_name: 'arena_persona' },
    },
    {
        key: 'live.arena.quotes', name: "Live: an Arena fighter's best lines",
        description: "From arena/arena-service.js generateQuotes (arena_quotes): the most quotable lines from raw speech-to-text.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["picks", "walkout", "voice_verdict", "mic_style"], "properties": {"picks": {"type": "array", "minItems": 1, "maxItems": 6, "items": {"type": "object", "additionalProperties": false, "required": ["index", "why"], "properties": {"index": {"type": "integer"}, "why": {"type": "string"}}}}, "walkout": {"type": "integer"}, "voice_verdict": {"type": "string"}, "mic_style": {"type": "string"}}},
        system_prompt: "You pick the most quotable lines a live-streamer actually said, from raw speech-to-text (expect transcription noise). Choose lines that are funny, savage, unhinged, weirdly profound, or perfect trash talk out of context — swearing and disrespect are a plus. Offensive or taboo language is allowed on this platform and is not a reason to skip a line. Skip only direct threats of violence, anything sexual about minors, doxxing, and lines that are pure transcription garbage. Prefer complete sentences. Return indexes into the list you are given. Output only the JSON.",
        user_prompt: "Lines (index: text):\n{{lines}}",
        default_route: 'live.summary', owner: 'live', metadata: { json_name: 'arena_quotes' },
    },
    {
        key: 'live.arena.headline', name: "Live: an Arena beef headline",
        description: "From arena/beef.js headlineFor (arena_headline).",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["headline"], "properties": {"headline": {"type": "string", "description": "≤ 100 chars, tabloid, inflammatory but funny, names both fighters"}}},
        system_prompt: "You write tabloid headlines for a streaming site's trash-talk arena: inflammatory, funny, screenshot-able, names both fighters, ≤ 100 chars. Profanity and disrespect welcome; this platform does not censor language. Hard line: no direct threats of violence, no doxxing. Output only the JSON.",
        user_prompt: "{{json payload}}",
        default_route: 'live.chat', owner: 'live', metadata: { json_name: 'arena_headline' },
    },
    {
        key: 'live.clips.confirm', name: "Live: is this chat spike clip-worthy",
        description: "From auto-clip-job.js (auto_clip_confirm): scene notes, transcript, sounds and chat around a spike.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["clip", "title", "desc"], "properties": {"clip": {"type": "boolean"}, "title": {"type": "string"}, "desc": {"type": "string"}}},
        system_prompt: "",
        user_prompt: "A live stream just had a spike in chat activity — viewers reacted to something. Decide if this is a genuinely clip-worthy standout moment (funny, dramatic, surprising, hype) worth auto-clipping, or just routine chatter.\n\nON SCREEN (recent scene notes):\n{{scene}}\n\nWHAT WAS SAID (recent transcript):\n{{script}}\n\nWHAT WAS HEARD (non-speech sounds detected):\n{{sounds}}\n\nCHAT (recent messages):\n{{chat}}\n\nReturn STRICT JSON only: {\"clip\": true|false, \"title\": \"<specific punchy 3-8 word title>\", \"desc\": \"<one vivid sentence>\"}. Set clip=false if nothing genuinely notable is happening.",
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'auto_clip_confirm' },
    },
    {
        key: 'live.chat.global', name: "Live: the global chat picture",
        description: "From chat-ai.js (chat_global): what the chat is about now, the running community notes, and 0-3 notable moments.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["recent_overview", "memory", "timeline"], "properties": {"recent_overview": {"type": "string"}, "memory": {"type": "string"}, "timeline": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["label", "detail", "mins_ago"], "properties": {"label": {"type": "string"}, "detail": {"type": "string"}, "mins_ago": {"type": "integer"}}}}}},
        system_prompt: "",
        user_prompt: "You are the community analyst for a live-streaming site's chat. Analyze the RECENT chat below (covers roughly the {{window_label}}, across the global room and individual streamer channels) and update a rolling picture of the community.\n\nReturn ONLY a JSON object, no prose, with exactly these keys:\n{\n  \"recent_overview\": \"2-4 sentences on what the chat is about right now: main topics, mood/energy, who's active, any notable events. Concrete, no fluff.\",\n  \"memory\": \"Condensed running notes about this community carried forward: recurring topics, regulars, running jokes, ongoing events/dramas. Update the PRIOR notes with anything new; keep it under ~1400 chars.\",\n  \"timeline\": [ {\"label\":\"short title\",\"detail\":\"one sentence\",\"mins_ago\": <integer: minutes before now this happened, read from the [Xm ago] markers on the messages>} ]  // 0-3 genuinely NOTABLE moments from THIS window (raids, milestones, big drama, memorable bits). Use [] if nothing stands out — do not invent.\n}\n\nPRIOR running notes (may be empty):\n\"\"\"{{prior_memory}}\"\"\"\n\nRecent timeline entries already recorded (avoid duplicating these):\n{{recent_labels}}\n\nRECENT CHAT ({{count}} messages, oldest first):\n{{messages}}",
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'chat_global' },
    },
    {
        key: 'live.chat.profile', name: "Live: one chatter today vs overall",
        description: "From chat-ai.js (chat_user, chat_relay, chat_anon): a signed-in, bridged or anonymous chatter.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["overview_24h", "overview_alltime", "memory", "timeline"], "properties": {"overview_24h": {"type": "string"}, "overview_alltime": {"type": "string"}, "memory": {"type": "string"}, "timeline": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["label", "detail", "mins_ago"], "properties": {"label": {"type": "string"}, "detail": {"type": "string"}, "mins_ago": {"type": "integer"}}}}}},
        system_prompt: "",
        user_prompt: "You profile {{subject}} on a live-streaming site, contrasting who they are TODAY vs OVERALL. Base everything only on the evidence below — do not invent.\n\nReturn ONLY a JSON object, no prose, with exactly these keys:\n{\n  \"overview_24h\": \"{{#recent}}2-3 sentences on what {{noun}} has been chatting about and their mood/energy in the LAST 24 HOURS.{{/recent}}{{^recent}}They have not chatted in the last 24h; write 1 sentence noting they have been quiet recently.{{/recent}}\",\n  \"overview_alltime\": \"2-3 sentences on who {{noun}} is as a chatter OVERALL: their style, recurring interests, tone, how they interact.\",\n  \"memory\": \"Condensed running notes about {{noun}} carried forward (interests, catchphrases, who they talk to, patterns). Update the PRIOR notes; keep under ~1000 chars.\",\n  \"timeline\": [ {\"label\":\"short title\",\"detail\":\"one sentence\",\"mins_ago\": <integer: minutes before now this happened, read from the [Xm ago] markers on the messages>} ]  // 0-2 NEW notable moments for {{noun}}, or [].\n}\n\nPRIOR running notes (all-time gist so far{{#seen}}; ~{{seen}} messages seen previously{{/seen}}):\n\"\"\"{{prior_memory}}\"\"\"\n\n{{messages_header}} (oldest first):\n{{messages}}",
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'chat_profile' },
    },
    {
        key: 'live.person.overview', name: "Live: a person as streamer and chatter",
        description: "From chat-ai-routes.js (combined_overview): two summaries fused into one.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["overview"], "properties": {"overview": {"type": "string"}}},
        system_prompt: "",
        user_prompt: "You are describing a person on a streaming site by fusing two AI summaries about them into ONE cohesive 2-4 sentence overview of who they are overall — both as a STREAMER and as a CHATTER. Be natural, specific, and not repetitive. Output ONLY the overview prose with no label or prefix.\n\nAS A STREAMER:\n{{as_streamer}}\n\nAS A CHATTER:\n{{as_chatter}}",
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'person_overview' },
    },
    {
        key: 'live.stream.titles', name: "Live: short titles for past sessions",
        description: "From chat-ai-routes.js (session_titles): a 3-6 word title per session summary.",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["titles"], "properties": {"titles": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["index", "title"], "properties": {"index": {"type": "integer"}, "title": {"type": "string"}}}}}},
        system_prompt: "",
        user_prompt: "Write a SHORT, catchy stream title for each livestream summary below — the way a real streamer titles a VOD: 3 to 6 words, punchy, no surrounding quotes, no trailing period. Match each stream's vibe.\n\n{{list}}\n\nReturn STRICT JSON only: {\"titles\": [{\"index\": <number>, \"title\": \"<3-6 word title>\"}]} with every item.",
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'session_titles' },
    },
    {
        key: 'live.moments.rank', name: "Live: rank VODs for the highlights showcase",
        description: "From ai-moments-job.js (moment_vod_rank).",
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["ranked"], "properties": {"ranked": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["index", "score", "why"], "properties": {"index": {"type": "integer"}, "score": {"type": "integer"}, "why": {"type": "string"}}}}}},
        system_prompt: "",
        user_prompt: "These are livestream VODs with their AI summaries and popularity stats. Rank the MOST interesting/entertaining/memorable ones for a highlights showcase — favor funny, dramatic, surprising, high-energy, or unusual content over routine \"just chatting / sitting at a desk\" streams. Clips taken and peak viewers are strong signals that something notable happened.\n\n{{list}}\n\nReturn STRICT JSON only, nothing else: {\"ranked\": [{\"index\": <n>, \"score\": <1-100>, \"why\": \"<3-8 words>\"}]} for the top {{top}}, best first.",
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'moment_vod_rank' },
    },
    {
        key: 'live.hero.slogans', name: 'Live: home hero audiences and quips',
        description: 'From slogan-job.js (hero_slogans): the rotating "Live streaming for …" audiences and one-liners, from the community\'s real chat, streamers and VODs.',
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["audiences", "quips"], "properties": {"audiences": {"type": "array", "items": {"type": "string"}}, "quips": {"type": "array", "items": {"type": "string"}}}},
        system_prompt: '',
        user_prompt: "You write the rotating hero copy for OpenVibe.Live — a scrappy, open-source, community-run live-streaming site at the heart of the OpenVibe network (\"Open Live Streaming\" — good vibes, no suits). Never call anything \"free\", \"$0\" or \"no cost\". Voice: witty, warm, self-aware, anti-corporate, meme-literate, a little unhinged — but ALWAYS kind, never punching down.\n\nEverything below is REAL data about THIS community right now. Lean into it hard: reference the actual people, running jokes, recurring topics, and memes so the copy feels like an inside joke the community is in on. Reference usernames by name in good fun (no @), and NEVER mock or embarrass anyone.\n\n=== GLOBAL CHAT VIBE (overview + memory + timeline) ===\n{{global}}\n\n=== PER-USER CHAT ANALYSIS (running jokes / personalities) ===\n{{users}}\n\n=== STREAMERS (what they stream) ===\n{{streamers}}\n\n=== RECENT VODS (what's been on) ===\n{{vods}}\n\n=== ACTIVE USERNAMES you may reference kindly ===\n{{usernames}}\n\n=== TASK ===\nProduce STRICT JSON, exactly this shape and nothing else:\n{\n  \"audiences\": [ {{target}} noun phrases naming WHO the site is for. The page prints the fixed headline \"Live streaming for {phrase}\" — you supply ONLY {phrase}. The words \"live\", \"streaming\", \"stream\", \"streamers\" and \"for\" must NOT appear anywhere in a phrase. Good: \"van-dwelling coders\", \"goosely's loyal 3 viewers\", \"crouton connoisseurs\". Bad: \"live streaming for coders\", \"coders live streaming\", \"for coders\". 1-5 words, lowercase (keep usernames' casing), plural people-nouns, no trailing punctuation. Mix on-theme audiences with community in-jokes drawn from the data. ],\n  \"quips\": [ {{target}} standalone one-liner taglines, punchy, <= 75 chars. Several should be clear references/memes about the real streamers, VODs, running jokes, or usernames above. ]\n}\nReturn ONLY the JSON object.",
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'hero_slogans' },
    },
    {
        key: 'live.easter_egg', name: 'Live: the daily secret code',
        description: 'From easter-egg-job.js (easter_egg): a Konami-style code with one fair clue per token.',
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["title", "code", "clues", "effect", "reward"], "properties": {"title": {"type": "string"}, "code": {"type": "array", "items": {"type": "string"}}, "clues": {"type": "array", "items": {"type": "string"}}, "effect": {"type": "string", "enum": ["confetti", "fireworks", "matrix", "rainbow", "shake"]}, "reward": {"type": "string"}}},
        system_prompt: '',
        user_prompt: "Invent today's secret \"Konami-style\" code for OpenVibe.Live, a hobbyist live-streaming site.{{#vibe}}\nToday's community vibe (for flavour only): {{vibe}}{{/vibe}}\nReturn STRICT JSON only, nothing else:\n{\n  \"title\": \"<punchy name for today's secret, 2-5 words>\",\n  \"code\": [<5 to 7 tokens IN ORDER, each exactly one of: \"up\",\"down\",\"left\",\"right\", or a single lowercase letter a-z; use at least 2 arrows and at least 1 letter>],\n  \"clues\": [<EXACTLY one clue per token, same order, each ≤ 90 chars>],\n  \"effect\": \"<one of: confetti, fireworks, matrix, rainbow, shake>\",\n  \"reward\": \"<a short, fun congratulatory line shown when a user cracks it>\"\n}\nCLUE RULES (this is a game people must actually be able to win):\n- Clue i describes token i and ONLY token i. Never list the token literally, but make it fair: a normal person should get it in one or two guesses.\n- Arrow clues use direction imagery (\"where the sun rises\" = right, \"toward the sky\" = up, \"the way rain falls\" = down, \"the side your heart is on\" = left).\n- Letter clues MUST quote a common word that starts with that exact letter, in quotes: \"the letter that starts 'goose'\" = g, \"'vibe' begins with it\" = v. Double-check the first letter of the quoted word.\n- Keep the flavour playful and on-theme, but clarity beats cleverness.",
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'easter_egg' },
    },
    {
        key: 'live.home.star', name: 'Live: Star of OpenVibe',
        description: 'From home/star-job.js (home_star): the streamer the home page features for a day, with a headline and a reason.',
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["username", "headline", "reason"], "properties": {"username": {"type": "string", "description": "exact username from the candidates"}, "headline": {"type": "string", "description": "≤ 60 chars"}, "reason": {"type": "string", "description": "≤ 170 chars, one sentence"}}},
        system_prompt: "You pick today's \"Star of OpenVibe\" — the one streamer OpenVibe.Live (a scrappy, open-source, community-run live-streaming site) rolls out the red carpet for on its home page for the next 24 hours.\nPick from the candidates ONLY (use the exact username). Spread the love: favour people who showed up and put in real hours, grew, got chat talking, or bring something different (a language, a niche, a robot, a vibe) — not just the biggest number. Small streamers who are consistent deserve their day. Never pick anyone in the \"recent stars\" list.\nWrite a \"headline\" (≤ 60 chars, punchy, warm, no quotes) and a \"reason\" (≤ 170 chars, one sentence, second person is fine, reference their real numbers or what they do — no emojis, no hashtags, no sarcasm, never mock). Output only JSON.",
        user_prompt: '{{json payload}}',
        default_route: 'live.summary', owner: 'live', metadata: { json_name: 'home_star' },
    },
    {
        key: 'live.arena.judge_beef', name: 'Live: Arena beef judge',
        description: 'From arena/listener.js judgeBeef (arena_beef_judge): is the newest speech still about the target, is it trash talk at them, how good, the best quotable line.',
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["about_target", "aimed_at_target", "quality", "best_line", "about", "announcer", "flagged"], "properties": {"about_target": {"type": "boolean", "description": "true if this speech is (still) about the target — by name OR by reference (\"he\", \"his stream\", \"that guy\", \"the beef\", continuing the same rant)"}, "aimed_at_target": {"type": "boolean", "description": "true if the speaker is trash-talking, roasting, calling out, dunking on or bragging over the target (in good fun) — requires about_target"}, "announcer": {"type": "string", "description": "one-line ring-announcer call of this moment, ≤ 110 chars, hype and funny (empty if not aimed at the target)"}, "quality": {"type": "integer", "minimum": 0, "maximum": 10, "description": "how good the trash talk is: spice, wit, specificity, quotability"}, "best_line": {"type": "string", "description": "the single best line: a COMPLETE sentence of at least 6 words that reads correctly on its own, words as spoken (fix casing/punctuation, drop stutters and filler, never change or add words). Empty if no clean line exists — a garbled fragment must not be quoted"}, "about": {"type": "string", "description": "≤ 10 words: what they said about the target"}, "flagged": {"type": "boolean", "description": "ONLY for direct threats of violence, sexual content about minors, or doxxing — never for offensive language"}}},
        system_prompt: "You judge live streamer-vs-streamer shit talk (battle-cam style). You get a target fighter's name(s), what the speaker ALREADY said about them a moment ago (context), and the newest ~60 seconds of the speaker's speech-to-text. The target may not be named again in the new speech — decide from context whether they are STILL talking about that person (\"he\", \"his chat\", \"that guy\", \"the beef\", the same story) or have moved on. DEFAULT TO about_target=false: gameplay chatter, mumbling and generic sentences are NOT about them even if their name was said a minute ago; if how_the_name_was_matched is not \"exact\" (a sound-alike), be extra strict. Then decide if the speech is talking shit AT or ABOUT the target (roast, callout, disrespect, bragging over them, trolling them) versus a neutral mention (shout-out, thanks, gameplay chatter). Savage, profane, petty and personal is GOOD and scores high — creativity, specificity and quotability score highest; lazy generic insults score low. Pick the best verbatim line, summarise what was said about the target in ≤ 10 words. Forgive transcription noise and misheard names. Offensive, provocative and taboo language — slurs included — is allowed on this platform and is NOT a reason to flag or to score low; judge the craft. Flag ONLY behavior: direct threats of violence, sexual content about minors, doxxing (addresses, phone numbers, private info). Output only the JSON.",
        user_prompt: '{{json payload}}',
        default_route: 'live.chat', owner: 'live', metadata: { json_name: 'arena_beef_judgement' },
    },
    {
        key: 'live.arena.judge_mic', name: 'Live: Arena mic judge',
        description: 'From arena/listener.js judgeMic (arena_mic_judge): is free mic chatter real trash talk with a clean quotable line.',
        input_schema: { type: 'object' },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["is_trash_talk", "garbled", "quality", "best_line", "about", "aimed_at", "announcer", "flagged"], "properties": {"is_trash_talk": {"type": "boolean", "description": "true ONLY if the speaker is actually talking shit: roasting, calling someone out, bragging over someone, ranting AT someone (chat, a group, a person), disrespect, trolling, \"come see me\" energy — AND there is a clean, complete, quotable line for it"}, "garbled": {"type": "boolean", "description": "true if the transcript is too mangled (misheard words, word salad, fragments) to quote a coherent line — then is_trash_talk must be false"}, "quality": {"type": "integer", "minimum": 0, "maximum": 10, "description": "how good the shit talk is: 8–10 = a stranger would laugh or screenshot it; 6–7 = solid, specific, quotable; ≤5 = generic, lazy or half a thought; 0 when not trash talk"}, "best_line": {"type": "string", "description": "the single best line: a COMPLETE sentence of at least 6 words that reads correctly on its own. Copy the words as spoken — you may fix casing and punctuation and drop stutters / filler (uh, um, repeated words) but never change, add or reorder words. Empty if no clean line exists"}, "about": {"type": "string", "description": "≤ 10 words: what the shit talk was about"}, "aimed_at": {"type": "string", "description": "who or what it is aimed at, as said or clearly implied: a streamer name, \"chat\", \"the mods\", \"twitch streamers\", a game, \"nobody\" — ≤ 6 words, lowercase"}, "announcer": {"type": "string", "description": "one-line ring-announcer call of the moment, ≤ 110 chars, hype and funny (empty if not trash talk)"}, "flagged": {"type": "boolean", "description": "ONLY for direct threats of violence, sexual content about minors, or doxxing — never for offensive language"}}},
        system_prompt: "You judge a live streamer's raw mic chatter for BATTLE-CAM style shit talk. You get ~60–90 seconds of speech-to-text — it is noisy: names get misheard, words get mangled, sentences get cut. DEFAULT TO is_trash_talk=false: gameplay narration, reading chat, small talk, \"um\", stories, neutral opinions → false, quality 0. Say true only when they are genuinely talking shit — roasting someone, calling someone out, bragging over someone, ranting AT chat or a group, disrespect, trolling, \"pull up\" energy — AND you can quote a clean, complete line for it. QUOTABILITY IS THE BAR: best_line must be a full sentence of at least 6 words that a reader understands with no context. If the good part is garbled or only a fragment, set garbled=true and is_trash_talk=false rather than quoting nonsense; a half-line in the feed is worse than nothing. Score the craft honestly: 8–10 only for lines a stranger would laugh at or screenshot; 6–7 solid and specific; 5 or below generic or lazy. Say who it is aimed at (a name if one is said or clearly meant, else \"chat\", \"the mods\", a group, a game, or \"nobody\"), summarise in ≤ 10 words, and write a one-line ring-announcer call. Offensive, provocative and taboo language — slurs included — is allowed on this platform and is NOT a reason to flag or to score low; judge the craft. Flag ONLY behavior: direct threats of violence, sexual content about minors, doxxing. Output only the JSON.",
        user_prompt: '{{json payload}}',
        default_route: 'live.chat', owner: 'live', metadata: { json_name: 'arena_mic_judgement' },
    },
    {
        key: 'live.moments.pick', name: 'Live: pick one moment of a VOD',
        description: 'From ai-moments-job.js _findBestMoment (moment_pick): the most interesting visible moment for a screenshot paste or a clip, away from moments already used.',
        input_schema: { type: 'object' },
        output_schema: {
            type: 'object', additionalProperties: false, required: ['t', 'title', 'desc'], properties: {
                t: { type: 'integer', description: 'seconds into the VOD' },
                title: { type: 'string', description: 'specific punchy 3-8 word title, not the stream name, funny, never generic' },
                desc: { type: 'string', description: 'one vivid sentence describing the moment' },
            },
        },
        system_prompt: '',
        user_prompt: 'Below is a single livestream VOD titled "{{title}}", described by its on-screen TIMELINE (visual scene notes) and its AUDIO TRANSCRIPT, each line timestamped [m:ss].\n\nTIMELINE:\n{{timeline}}\n\nTRANSCRIPT:\n{{transcript}}\n\nSOUNDS HEARD (non-speech audio events):\n{{sounds}}\n\nViewers CLIPPED these timestamps (very strong "this was a highlight" signal): {{clipped}}\nChat activity SPIKED around: {{spikes}}\n\n{{flavor_hint}}\n{{#avoid}}ALREADY USED (a paste or clip exists there) — do NOT pick these or anything within 2 minutes of them: {{avoid}}. Find a DIFFERENT moment.{{/avoid}}\n\nFind the SINGLE most interesting/funny/dramatic/surprising/striking moment in this VOD with something clearly VISIBLE happening. Prefer moments backed by the clip/chat signals when they line up with something notable. NEVER pick a black/dark/loading/blank screen, an intro/BRB card, or a moment with no visible content or activity. Return STRICT JSON only, nothing else: {"t": <seconds into the vod>, "title": "<specific punchy 3-8 word title, not the stream name, funny, never generic>", "desc": "<one vivid sentence describing the moment>"}',
        default_route: 'live.legacy', owner: 'live', metadata: { json_name: 'moment_pick' },
    },
    {
        key: 'live.stream.recap', name: 'Live: after-show report',
        description: 'From recap/recap.js aiWriteup (stream_recap).',
        input_schema: { type: 'object' },
        output_schema: {
            type: 'object', additionalProperties: false, required: ['headline', 'summary', 'moment', 'tags', 'grade'], properties: {
                headline: { type: 'string', description: '≤ 70 chars, like a sports-page headline about this stream, no quotes, no emojis' },
                summary: { type: 'string', description: '2–3 sentences, ≤ 420 chars, what happened and how it went, concrete, warm, second person is fine' },
                moment: { type: 'string', description: '≤ 160 chars, the single moment of the night (from the mic lines, chat spike, a clip title or the transcript) — or empty string' },
                tags: { type: 'array', items: { type: 'string' }, description: '3 short vibe tags, 1–2 words each, lowercase' },
                grade: { type: 'string', enum: ['S', 'A', 'B', 'C'], description: 'S = legendary night, A = great, B = solid, C = quiet' },
            },
        },
        system_prompt: 'You write the "after-show report" for a live stream on OpenVibe.Live (a scrappy, open-source, community-run streaming site). Voice: sports-page energy, warm, specific, a little funny, never mocking the streamer or the viewers. Use the REAL numbers and names given. Small streams are fine — a 4-viewer night can still be an A if it was fun. Output only JSON.',
        user_prompt: '{{json facts}}',
        default_route: 'live.summary', owner: 'live', metadata: { json_name: 'stream_recap' },
    },
    {
        key: 'network.site_copy', name: 'Network: shared footer copy',
        description: 'Was Live\'s POST /internal/ai/site-copy (server/internal/routes.js). The model writes blurbs and PICKS link ids from an allow-list; it never returns URLs or markup.',
        input_schema: { type: 'object' },
        output_schema: {
            type: 'object', additionalProperties: false, required: ['sites'], properties: {
                sites: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['id', 'blurb', 'picks'], properties: { id: { type: 'string' }, blurb: { type: 'string' }, picks: { type: 'array', items: { type: 'string' } } } } },
            },
        },
        system_prompt: 'You write footer copy for OpenVibe, an open source, community-run network of sites (live streaming, online tools, community pastes, games, media). Voice: plain, confident, specific, a little playful. Never claim anything is free, costs $0, or has no ads. No hype words, no emoji, no markup, no URLs. For each site write one blurb of at most 150 characters saying what a visitor can do there right now, and choose 4 link ids from the provided list that a visitor of that site would most likely want next (prefer other sites and popular tools; never the site itself).',
        user_prompt: '{{json payload}}',
        default_route: 'live.summary', owner: 'network', metadata: { json_name: 'site_copy' },
    },
];

// ── Structured workflows ─────────────────────────────────
const TEXT_OUT = (props, required) => ({ type: 'object', additionalProperties: false, required, properties: props });

const structured = [
    {
        key: 'live.translate', name: 'Translate a chat line, bio or speech lines', namespace: 'live',
        description: 'Direction is chosen by the caller (Live picks it from the script and the channel language). Cached per service: translations of public text are the same for every Live user.',
        input_schema: TEXT_OUT({ text: STR(4000), from: LANG, to: LANG, context: { enum: ['chat', 'bio', 'speech'] }, max_tokens: { type: 'integer', minimum: 40, maximum: 1200 } }, ['text', 'to']),
        output_schema: TEXT_OUT({ text: { type: ['string', 'null'] }, from: STR(8), to: STR(8), unchanged: { type: 'boolean' }, reason: STR(40) }, ['text', 'unchanged']),
        steps: [{ kind: 'llm', template: 'live.translate', operation: 'generate', output: 'text', prepare: 'live.translate', postprocess: 'live.translate', params: { temperature: 0.2, timeout_ms: 15000 } }],
        cache_mode: 'service', cache_ttl_sec: 30 * 24 * 3600,
    },
    {
        key: 'live.paste.describe_image', name: 'Describe an image paste / moment frame', namespace: 'live',
        input_schema: TEXT_OUT({ title: STR(500), image: IMAGE, sources: SOURCES(0, 5) }, ['image']),
        output_schema: TEXT_OUT({ description: STR(600), tags: { type: 'array', items: STR(200), maxItems: 8 } }, ['description', 'tags']),
        steps: [{ kind: 'llm', template: 'live.paste.describe_image', operation: 'generate', output: 'text', image: 'image', image_max_width: 1280, prepare: 'live.paste.describe_image', postprocess: 'live.paste.describe_image', params: { max_tokens: 300 } }],
        cache_mode: 'private',
    },
    {
        key: 'live.paste.summarize_text', name: 'Summarize a text paste', namespace: 'live',
        input_schema: TEXT_OUT({ title: STR(500), content: STR(200000), sources: SOURCES(0, 5) }, ['content']),
        output_schema: TEXT_OUT({ description: STR(300), tags: { type: 'array', maxItems: 0 } }, ['description', 'tags']),
        steps: [{ kind: 'llm', template: 'live.paste.summarize_text', operation: 'summarize', output: 'text', prepare: 'live.paste.summarize_text', postprocess: 'live.paste.summarize_text', params: { max_tokens: 120 } }],
        cache_mode: 'private',
    },
    {
        key: 'live.stream.describe_frame', name: 'Describe a live-stream frame (moment detection)', namespace: 'live',
        input_schema: TEXT_OUT({ image: IMAGE, sources: SOURCES(0, 5) }, ['image']),
        output_schema: TEXT_OUT({ description: STR(400), tags: { type: 'array', items: STR(200), maxItems: 6 }, worthy: { type: 'boolean' }, title: STR(80) }, ['description', 'tags', 'worthy', 'title']),
        steps: [{ kind: 'llm', template: 'live.stream.describe_frame', operation: 'generate', output: 'text', image: 'image', image_max_width: 768, postprocess: 'live.stream.describe_frame', params: { max_tokens: 240 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.stream.summarize', name: 'Stream overview + inferred category (stream memory)', namespace: 'live',
        input_schema: TEXT_OUT({
            observations: { type: 'array', items: STR(1000), minItems: 1, maxItems: 400 },
            speech: { type: 'array', maxItems: 1000, items: { type: 'object', required: ['start_sec', 'text'], properties: { start_sec: { type: 'number' }, text: STR(2000) } } },
            sounds: { type: 'array', maxItems: 500, items: { type: 'object', required: ['start_sec', 'label'], properties: { start_sec: { type: 'number' }, label: STR(120), confidence: { type: 'number' } } } },
            sources: SOURCES(0, 50),
        }, ['observations']),
        output_schema: TEXT_OUT({ overview: STR(2000), category: { type: ['string', 'null'], enum: ['outdoors', 'travel', 'building', 'music', 'gaming', 'robot', 'desktop', 'irl', 'other', null] }, tags: { type: 'array', items: STR(200), maxItems: 6 } }, ['overview', 'category', 'tags']),
        steps: [{ kind: 'llm', template: 'live.stream.summarize', operation: 'summarize', output: 'text', prepare: 'live.stream.summarize', postprocess: 'live.stream.summarize', params: { max_tokens: 560 } }],
        cache_mode: 'private',
    },
    {
        key: 'live.streamer.overview', name: 'Internal streamer overview for staff', namespace: 'live',
        input_schema: TEXT_OUT({
            streamer: { type: 'object', required: ['username'], properties: { username: STR(80), display_name: STR(120), bio: STR(2000), category: STR(40), category_inferred: { type: 'boolean' } } },
            memories: { type: 'array', items: STR(1000), maxItems: 100 },
            vods: { type: 'array', maxItems: 50, items: { type: 'object', properties: { title: STR(300), category: STR(40) } } },
            pastes: { type: 'array', maxItems: 50, items: { type: 'object', properties: { title: STR(300), summary: STR(600) } } },
            sources: SOURCES(0, 50),
        }, ['streamer']),
        output_schema: TEXT_OUT({ overview: STR(4000) }, ['overview']),
        steps: [{ kind: 'llm', template: 'live.streamer.overview', operation: 'summarize', output: 'text', prepare: 'live.streamer.overview', postprocess: 'live.streamer.overview', params: { max_tokens: 550 } }],
        cache_mode: 'private',
    },
    {
        key: 'live.media.overview', name: 'VOD/clip overview from frames and transcript', namespace: 'live',
        input_schema: TEXT_OUT({ frames: { type: 'array', items: STR(1000), maxItems: 60 }, transcript: STR(200000), sources: SOURCES(0, 50) }, []),
        output_schema: TEXT_OUT({ overview: STR(2000) }, ['overview']),
        steps: [{ kind: 'llm', template: 'live.media.overview', operation: 'summarize', output: 'text', prepare: 'live.media.overview', postprocess: 'live.media.overview', params: { max_tokens: 400 } }],
        cache_mode: 'private',
    },
    {
        key: 'live.viewers.plan', name: "AI viewers: director plan", namespace: 'live',
        description: "The director Live used to prompt (viewers/director.js), now a versioned template: the stream's stable context and its volatile tail in (Live builds both from the roster, settings, transcript and chat), a plan of up to max_lines lines out. Runs on a streamer's own key when the run names their credential.",
        input_schema: TEXT_OUT({ stable: { type: 'string', maxLength: 40000 }, volatile: { type: 'string', maxLength: 60000 }, max_lines: { type: 'integer', minimum: 1, maximum: 12 }, temperature: { type: 'number', minimum: 0, maximum: 2 } }, ['stable', 'volatile']),
        output_schema: {"type": "object", "additionalProperties": false, "properties": {"skip": {"type": "boolean", "description": "true when nothing worth saying right now"}, "notes": {"type": "string", "description": "one short line of director reasoning (logged only)"}, "lines": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"bot": {"type": "string", "description": "username of the AI viewer that speaks"}, "target": {"type": "string", "enum": ["viewer", "bot", "streamer", "ambient"]}, "reply_to": {"type": ["string", "null"], "description": "username being replied to (viewer or bot), else null"}, "thread": {"type": ["string", "null"], "description": "existing thread id as a string, \"new\" to start one, or null"}, "topic": {"type": ["string", "null"], "description": "topic label when thread is \"new\""}, "delay_ms": {"type": "integer", "minimum": 0, "maximum": 45000}, "text": {"type": "string", "description": "the chat line, in character"}, "reason": {"type": "string", "description": "why this bot says this now (<= 80 chars)"}}, "required": ["bot", "target", "reply_to", "thread", "topic", "delay_ms", "text", "reason"]}}, "threads_close": {"type": "array", "items": {"type": "string"}, "description": "thread ids that reached a natural end"}}, "required": ["skip", "notes", "lines", "threads_close"]},
        steps: [{ kind: 'llm', template: 'live.viewers.plan', operation: 'generate', output: 'json', prepare: 'live.viewers.plan', postprocess: 'live.viewers.plan', params: { timeout_ms: 25000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.viewers.reply', name: "AI viewers: fast streamer reply", namespace: 'live',
        description: "One line from one viewer answering the streamer (viewers/director.js quickReply).",
        input_schema: TEXT_OUT({ stable: { type: 'string', maxLength: 40000 }, situation: { type: 'string', maxLength: 20000 }, bot: STR(80), streamer_line: STR(400), max_words: { type: 'integer', minimum: 1, maximum: 80 } }, ['stable', 'bot', 'streamer_line']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["text"], "properties": {"text": {"type": "string"}}},
        steps: [{ kind: 'llm', template: 'live.viewers.reply', operation: 'generate', output: 'text', prepare: 'live.viewers.reply', postprocess: 'live.viewers.reply', params: { max_tokens: 70, temperature: 0.9, timeout_ms: 20000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.viewers.fold', name: "AI viewers: memory fold", namespace: 'live',
        description: "Every viewer's recent lines folded into its memory, plus the channel memory (viewers/fold.js).",
        input_schema: TEXT_OUT({ channel_memory: STR(2000), personas: { type: 'array', minItems: 1, maxItems: 30, items: { type: 'object', required: ['username', 'lines'], additionalProperties: false, properties: { username: STR(80), memory: STR(2000), lines: { type: 'array', maxItems: 20, items: STR(400) } } } } }, ['personas']),
        output_schema: {"type": "object", "additionalProperties": false, "properties": {"memories": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"bot": {"type": "string"}, "memory": {"type": "string"}}, "required": ["bot", "memory"]}}, "channel_memory": {"type": "string", "description": "running jokes / recurring topics for the whole channel, <= 90 words"}}, "required": ["memories", "channel_memory"]},
        steps: [{ kind: 'llm', template: 'live.viewers.fold', operation: 'generate', output: 'json', prepare: 'live.viewers.fold', postprocess: 'live.viewers.fold', params: { temperature: 0.4, timeout_ms: 30000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.viewers.clone', name: "AI viewers: brief for a cloned chatter", namespace: 'live',
        description: "A character brief from what is known about a real viewer, so a clone bot can play them (viewers/roster.js).",
        input_schema: TEXT_OUT({ name: STR(120), overview: STR(2000), memory: STR(2000), samples: { type: 'array', maxItems: 24, items: STR(400) } }, ['name']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["text"], "properties": {"text": {"type": "string"}}},
        steps: [{ kind: 'llm', template: 'live.viewers.clone', operation: 'generate', output: 'text', prepare: 'live.viewers.clone', postprocess: 'live.viewers.clone', params: { max_tokens: 160, temperature: 0.7, timeout_ms: 20000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.arena.persona', name: "Arena fighter persona", namespace: 'live',
        description: "The prompt Live used to render (arena-service.js), now a versioned template: the fighter's facts in (numbers, what they said, their shit talk, rivals); the persona out.",
        input_schema: TEXT_OUT({ facts: { type: 'object' } }, ['facts']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["fighter_name", "title", "class", "element", "signature_move", "special", "weakness", "taunt", "taunts", "typing_style", "spoken_as", "custom_stats", "lore", "catchphrase", "entrance_music", "stat_quips"], "properties": {"fighter_name": {"type": "string", "description": "Arena ring name, 2–5 words, based on the streamer"}, "title": {"type": "string", "description": "Epithet like \"The Midnight Menace of Cozy Corner\""}, "class": {"type": "string", "description": "Fighting-game archetype, e.g. Grappler, Zoner, Rushdown, Summoner, Bard, Tank"}, "element": {"type": "string", "description": "Single word element/vibe"}, "signature_move": {"type": "object", "additionalProperties": false, "required": ["name", "description"], "properties": {"name": {"type": "string"}, "description": {"type": "string"}}}, "special": {"type": "object", "additionalProperties": false, "required": ["name", "description"], "properties": {"name": {"type": "string"}, "description": {"type": "string"}}}, "weakness": {"type": "string"}, "taunt": {"type": "string", "description": "Their signature ragebait line: one sentence, written EXACTLY the way this person types/talks (their punctuation, caps, slang, emoji habits, typos), aimed at rivals or their chat, designed to make people reply"}, "taunts": {"type": "array", "minItems": 3, "maxItems": 3, "items": {"type": "string"}, "description": "three more ragebait/troll lines in their own voice: one at a specific rival from the roster, one at their own chat, one about a topic they will not shut up about"}, "typing_style": {"type": "string", "description": "≤ 12 words describing how they TALK on mic (e.g. \"mumbles, calls everyone bud, yells at chat every 30 seconds\")"}, "custom_stats": {"type": "array", "minItems": 6, "maxItems": 6, "items": {"type": "object", "additionalProperties": false, "required": ["name", "value", "quip"], "properties": {"name": {"type": "string", "description": "≤ 14 chars, a stat that only makes sense for THIS person — named after their actual bits, habits, subjects, gear, rivals, the way they talk (e.g. \"Alt Accounts\", \"Tent Smell\", \"Baby Voice\", \"Reads Chat\", \"Cope\")"}, "value": {"type": "integer", "minimum": 1, "maximum": 99}, "quip": {"type": "string", "description": "≤ 8 words, in their own speaking voice"}}}, "description": "six CHARACTERISTICS unique to this streamer for their radar — read from what they SAY ON MIC (things_they_said_on_stream, their_best_shit_talk, who_they_call_out, what_they_rant_at) and their channel (ai_overview, what the camera saw): the bits they run, what they will not shut up about, how they treat chat, their rivals, their gear obsession, their schedule. Names must be specific to THEM (never generic like \"Hype\" or \"Skill\"), funny, ragebait-ish; values honestly spread (at least one under 30, at least one over 85) and the quip explains the number in their voice."}, "spoken_as": {"type": "array", "minItems": 2, "maxItems": 6, "items": {"type": "string"}, "description": "how OTHER people say or mishear this streamer's name out loud, as a speech-to-text engine would write it: nicknames, shortenings, phonetic misspellings, the handle split into words (e.g. \"japanese old guy\", \"matticus\", \"goose lee\", \"dan\") — lowercase"}, "lore": {"type": "string", "description": "2–3 sentence character-select bio"}, "catchphrase": {"type": "string"}, "entrance_music": {"type": "string"}, "stat_quips": {"type": "object", "additionalProperties": false, "required": ["heat", "aim", "kills", "mouth", "clapback", "stamina", "pace"], "properties": {"heat": {"type": "string", "description": "≤ 8 words explaining their heat rating in character"}, "aim": {"type": "string", "description": "≤ 8 words explaining their aim rating in character"}, "kills": {"type": "string", "description": "≤ 8 words explaining their kills rating in character"}, "mouth": {"type": "string", "description": "≤ 8 words explaining their mouth rating in character"}, "clapback": {"type": "string", "description": "≤ 8 words explaining their clapback rating in character"}, "stamina": {"type": "string", "description": "≤ 8 words explaining their stamina rating in character"}, "pace": {"type": "string", "description": "≤ 8 words explaining their pace rating in character"}}}}},
        steps: [{ kind: 'llm', template: 'live.arena.persona', operation: 'generate', output: 'json', prepare: 'live.arena.persona', postprocess: 'live.arena.persona', params: { max_tokens: 1200, temperature: 0.95, timeout_ms: 30000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.arena.quotes', name: "Arena fighter best lines", namespace: 'live',
        description: "The prompt Live used to render (arena-service.js): candidate lines in, picks by index, a walkout line and a voice verdict out.",
        input_schema: TEXT_OUT({ lines: { type: 'array', minItems: 1, maxItems: 120, items: STR(400) } }, ['lines']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["picks", "walkout", "voice_verdict", "mic_style"], "properties": {"picks": {"type": "array", "minItems": 1, "maxItems": 6, "items": {"type": "object", "additionalProperties": false, "required": ["index", "why"], "properties": {"index": {"type": "integer"}, "why": {"type": "string"}}}}, "walkout": {"type": "integer"}, "voice_verdict": {"type": "string"}, "mic_style": {"type": "string"}}},
        steps: [{ kind: 'llm', template: 'live.arena.quotes', operation: 'generate', output: 'json', prepare: 'live.arena.quotes', postprocess: 'live.arena.quotes', params: { max_tokens: 500, temperature: 0.7, timeout_ms: 30000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.arena.headline', name: "Arena beef headline", namespace: 'live',
        description: "The prompt Live used to render (beef.js): the event (open, forfeit, score) and its fighters in; a tabloid headline out.",
        input_schema: { type: 'object', required: ['kind'], properties: { kind: { enum: ['open', 'forfeit', 'score'] } } },
        output_schema: {"type": "object", "additionalProperties": false, "required": ["headline"], "properties": {"headline": {"type": "string", "description": "≤ 100 chars, tabloid, inflammatory but funny, names both fighters"}}},
        steps: [{ kind: 'llm', template: 'live.arena.headline', operation: 'generate', output: 'json', prepare: 'live.arena.headline', postprocess: 'live.arena.headline', params: { max_tokens: 80, temperature: 1.0, timeout_ms: 15000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.clips.confirm', name: "Is this chat spike clip-worthy", namespace: 'live',
        description: "The prompt Live used to render (auto-clip-job.js): scene notes, timed speech and sounds, and chat around a spike in; clip or not, with a title, out.",
        input_schema: TEXT_OUT({ scene: { type: 'array', maxItems: 40, items: STR(1000) }, transcript: { type: 'array', maxItems: 60, items: { type: 'object', required: ['t', 'text'], additionalProperties: false, properties: { t: { type: 'number', minimum: 0 }, text: STR(1000) } } }, sounds: { type: 'array', maxItems: 40, items: { type: 'object', required: ['t', 'label'], additionalProperties: false, properties: { t: { type: 'number', minimum: 0 }, label: STR(120), confidence: { type: 'number' } } } }, chat: { type: 'array', maxItems: 60, items: STR(1000) } }, []),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["clip", "title", "desc"], "properties": {"clip": {"type": "boolean"}, "title": {"type": "string"}, "desc": {"type": "string"}}},
        steps: [{ kind: 'llm', template: 'live.clips.confirm', operation: 'generate', output: 'json', prepare: 'live.clips.confirm', postprocess: 'live.clips.confirm', params: { max_tokens: 220 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.chat.global', name: "The global chat picture", namespace: 'live',
        description: "The prompt Live used to render (chat-ai.js), now a versioned template: the window, the prior notes, moments already recorded and the recent messages in.",
        input_schema: TEXT_OUT({ window_label: STR(40), prior_memory: STR(4000), recent_labels: { type: 'array', maxItems: 20, items: STR(200) }, messages: { type: 'array', maxItems: 300, items: { type: 'object', required: ['author', 'text'], additionalProperties: false, properties: { mins_ago: { type: ['integer', 'null'], minimum: 0 }, where: { type: ['string', 'null'], maxLength: 80 }, author: STR(80), kind: { type: ['string', 'null'], maxLength: 40 }, text: STR(1000) } } } }, ['messages']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["recent_overview", "memory", "timeline"], "properties": {"recent_overview": {"type": "string"}, "memory": {"type": "string"}, "timeline": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["label", "detail", "mins_ago"], "properties": {"label": {"type": "string"}, "detail": {"type": "string"}, "mins_ago": {"type": "integer"}}}}}},
        steps: [{ kind: 'llm', template: 'live.chat.global', operation: 'generate', output: 'json', prepare: 'live.chat.global', postprocess: 'live.chat.insight', params: { max_tokens: 700 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.chat.profile', name: "One chatter today vs overall", namespace: 'live',
        description: "The prompt Live used to render for signed-in, bridged and anonymous chatters (chat-ai.js), now one versioned template.",
        input_schema: TEXT_OUT({ subject_kind: { enum: ['user', 'relay', 'anon'] }, name: STR(120), platform: STR(40), recent_24h: { type: 'boolean' }, seen: { type: 'integer', minimum: 0 }, prior_memory: STR(4000), messages: { type: 'array', maxItems: 300, items: { type: 'object', required: ['author', 'text'], additionalProperties: false, properties: { mins_ago: { type: ['integer', 'null'], minimum: 0 }, where: { type: ['string', 'null'], maxLength: 80 }, author: STR(80), kind: { type: ['string', 'null'], maxLength: 40 }, text: STR(1000) } } } }, ['subject_kind', 'name', 'messages']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["overview_24h", "overview_alltime", "memory", "timeline"], "properties": {"overview_24h": {"type": "string"}, "overview_alltime": {"type": "string"}, "memory": {"type": "string"}, "timeline": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["label", "detail", "mins_ago"], "properties": {"label": {"type": "string"}, "detail": {"type": "string"}, "mins_ago": {"type": "integer"}}}}}},
        steps: [{ kind: 'llm', template: 'live.chat.profile', operation: 'generate', output: 'json', prepare: 'live.chat.profile', postprocess: 'live.chat.insight', params: { max_tokens: 600 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.person.overview', name: "A person as streamer and chatter", namespace: 'live',
        description: "The prompt Live used to render (chat-ai-routes.js combined_overview).",
        input_schema: TEXT_OUT({ as_streamer: { type: 'string', minLength: 1, maxLength: 4000 }, as_chatter: { type: 'string', minLength: 1, maxLength: 4000 } }, ['as_streamer', 'as_chatter']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["overview"], "properties": {"overview": {"type": "string"}}},
        steps: [{ kind: 'llm', template: 'live.person.overview', operation: 'generate', output: 'json', prepare: 'live.person.overview', postprocess: 'live.person.overview', params: { max_tokens: 320 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.stream.titles', name: "Short titles for past sessions", namespace: 'live',
        description: "The prompt Live used to render (chat-ai-routes.js session_titles): session summaries in, a title per index out.",
        input_schema: TEXT_OUT({ summaries: { type: 'array', minItems: 1, maxItems: 20, items: STR(1000) } }, ['summaries']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["titles"], "properties": {"titles": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["index", "title"], "properties": {"index": {"type": "integer"}, "title": {"type": "string"}}}}}},
        steps: [{ kind: 'llm', template: 'live.stream.titles', operation: 'generate', output: 'json', prepare: 'live.stream.titles', postprocess: 'live.stream.titles', params: { max_tokens: 700 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.moments.rank', name: "Rank VODs for the highlights showcase", namespace: 'live',
        description: "The prompt Live used to render (ai-moments-job.js): VODs with their summaries and stats in, the top ones scored out.",
        input_schema: TEXT_OUT({ vods: { type: 'array', minItems: 1, maxItems: 25, items: { type: 'object', required: ['title'], additionalProperties: false, properties: { title: STR(200), overview: STR(1000), views: { type: 'integer', minimum: 0 }, clips: { type: 'integer', minimum: 0 }, peak_viewers: { type: 'integer', minimum: 0 } } } }, want: { type: 'integer', minimum: 1, maximum: 25 } }, ['vods']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["ranked"], "properties": {"ranked": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["index", "score", "why"], "properties": {"index": {"type": "integer"}, "score": {"type": "integer"}, "why": {"type": "string"}}}}}},
        steps: [{ kind: 'llm', template: 'live.moments.rank', operation: 'generate', output: 'json', prepare: 'live.moments.rank', postprocess: 'live.moments.rank', params: { max_tokens: 700 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.hero.slogans', name: 'Home hero audiences and quips', namespace: 'live',
        description: 'The prompt Live used to render (slogan-job.js), now a versioned template: the chat vibe, per-user notes, streamers, recent VODs and active usernames in; audiences and quips out. Live keeps its cleaning rules (no "free", no "streaming for").',
        input_schema: TEXT_OUT({
            global: STR(4000), users: { type: 'array', maxItems: 20, items: { type: 'object', required: ['name', 'text'], additionalProperties: false, properties: { name: STR(120), text: STR(1000) } } }, streamers: { type: 'array', maxItems: 20, items: { type: 'object', required: ['name', 'text'], additionalProperties: false, properties: { name: STR(120), text: STR(1000) } } }, vods: { type: 'array', maxItems: 20, items: { type: 'object', required: ['name', 'text'], additionalProperties: false, properties: { name: STR(120), text: STR(1000) } } },
            usernames: { type: 'array', maxItems: 40, items: STR(64) }, count: { type: 'integer', minimum: 1, maximum: 40 },
        }, []),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["audiences", "quips"], "properties": {"audiences": {"type": "array", "items": {"type": "string"}}, "quips": {"type": "array", "items": {"type": "string"}}}},
        steps: [{ kind: 'llm', template: 'live.hero.slogans', operation: 'generate', output: 'json', prepare: 'live.hero.slogans', postprocess: 'live.hero.slogans', params: { max_tokens: 1700 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.easter_egg', name: 'The daily secret code', namespace: 'live',
        description: 'The prompt Live used to render (easter-egg-job.js), now a versioned template: today\'s vibe in (optional); a code, clues, effect and reward out. Live checks every clue and replaces any that do not point at its token.',
        input_schema: TEXT_OUT({ vibe: STR(1000) }, []),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["title", "code", "clues", "effect", "reward"], "properties": {"title": {"type": "string"}, "code": {"type": "array", "items": {"type": "string"}}, "clues": {"type": "array", "items": {"type": "string"}}, "effect": {"type": "string", "enum": ["confetti", "fireworks", "matrix", "rainbow", "shake"]}, "reward": {"type": "string"}}},
        steps: [{ kind: 'llm', template: 'live.easter_egg', operation: 'generate', output: 'json', prepare: 'live.easter_egg', postprocess: 'live.easter_egg', params: { max_tokens: 600 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.home.star', name: 'Star of OpenVibe', namespace: 'live',
        description: 'The prompt Live used to render (home/star-job.js), now a versioned template: recent stars, the previous star and up to 25 candidates with their numbers in; one username, a headline and a reason out.',
        input_schema: TEXT_OUT({
            recent_stars: { type: 'array', maxItems: 40, items: STR(64) }, previous_star: { type: ['string', 'null'], maxLength: 64 },
            candidates: { type: 'array', minItems: 1, maxItems: 25, items: { type: 'object', required: ['username'], properties: { username: STR(64) } } },
        }, ['candidates']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["username", "headline", "reason"], "properties": {"username": {"type": "string", "description": "exact username from the candidates"}, "headline": {"type": "string", "description": "≤ 60 chars"}, "reason": {"type": "string", "description": "≤ 170 chars, one sentence"}}},
        steps: [{ kind: 'llm', template: 'live.home.star', operation: 'generate', output: 'json', prepare: 'live.home.star', postprocess: 'live.home.star', params: { max_tokens: 300, temperature: 0.9, timeout_ms: 30000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.arena.judge_beef', name: 'Arena: judge a callout at another fighter', namespace: 'live',
        description: 'The prompt Live used to render (arena/listener.js), now a versioned template: the target names, how the name was heard, what was already said about them, and the newest speech in; the judgement out.',
        input_schema: TEXT_OUT({
            target_names: { type: 'array', minItems: 1, maxItems: 8, items: STR(120) },
            target_as_transcribed: { type: 'array', maxItems: 8, items: STR(120) },
            target_named_in_new_speech: { type: 'boolean' },
            how_the_name_was_matched: STR(40),
            what_speaker_already_said_about_target: { type: ['string', 'null'], maxLength: 4000 },
            new_speech: { type: 'string', minLength: 1, maxLength: 6000 },
        }, ['target_names', 'new_speech']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["about_target", "aimed_at_target", "quality", "best_line", "about", "announcer", "flagged"], "properties": {"about_target": {"type": "boolean", "description": "true if this speech is (still) about the target — by name OR by reference (\"he\", \"his stream\", \"that guy\", \"the beef\", continuing the same rant)"}, "aimed_at_target": {"type": "boolean", "description": "true if the speaker is trash-talking, roasting, calling out, dunking on or bragging over the target (in good fun) — requires about_target"}, "announcer": {"type": "string", "description": "one-line ring-announcer call of this moment, ≤ 110 chars, hype and funny (empty if not aimed at the target)"}, "quality": {"type": "integer", "minimum": 0, "maximum": 10, "description": "how good the trash talk is: spice, wit, specificity, quotability"}, "best_line": {"type": "string", "description": "the single best line: a COMPLETE sentence of at least 6 words that reads correctly on its own, words as spoken (fix casing/punctuation, drop stutters and filler, never change or add words). Empty if no clean line exists — a garbled fragment must not be quoted"}, "about": {"type": "string", "description": "≤ 10 words: what they said about the target"}, "flagged": {"type": "boolean", "description": "ONLY for direct threats of violence, sexual content about minors, or doxxing — never for offensive language"}}},
        steps: [{ kind: 'llm', template: 'live.arena.judge_beef', operation: 'generate', output: 'json', prepare: 'live.arena.judge_beef', postprocess: 'live.arena.judge', params: { max_tokens: 240, temperature: 0.4, timeout_ms: 25000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.arena.judge_mic', name: 'Arena: judge free mic chatter', namespace: 'live',
        description: 'The prompt Live used to render (arena/listener.js), now a versioned template: 60-90 seconds of speech in; whether it is quotable trash talk out.',
        input_schema: TEXT_OUT({ speech: { type: 'string', minLength: 1, maxLength: 6000 } }, ['speech']),
        output_schema: {"type": "object", "additionalProperties": false, "required": ["is_trash_talk", "garbled", "quality", "best_line", "about", "aimed_at", "announcer", "flagged"], "properties": {"is_trash_talk": {"type": "boolean", "description": "true ONLY if the speaker is actually talking shit: roasting, calling someone out, bragging over someone, ranting AT someone (chat, a group, a person), disrespect, trolling, \"come see me\" energy — AND there is a clean, complete, quotable line for it"}, "garbled": {"type": "boolean", "description": "true if the transcript is too mangled (misheard words, word salad, fragments) to quote a coherent line — then is_trash_talk must be false"}, "quality": {"type": "integer", "minimum": 0, "maximum": 10, "description": "how good the shit talk is: 8–10 = a stranger would laugh or screenshot it; 6–7 = solid, specific, quotable; ≤5 = generic, lazy or half a thought; 0 when not trash talk"}, "best_line": {"type": "string", "description": "the single best line: a COMPLETE sentence of at least 6 words that reads correctly on its own. Copy the words as spoken — you may fix casing and punctuation and drop stutters / filler (uh, um, repeated words) but never change, add or reorder words. Empty if no clean line exists"}, "about": {"type": "string", "description": "≤ 10 words: what the shit talk was about"}, "aimed_at": {"type": "string", "description": "who or what it is aimed at, as said or clearly implied: a streamer name, \"chat\", \"the mods\", \"twitch streamers\", a game, \"nobody\" — ≤ 6 words, lowercase"}, "announcer": {"type": "string", "description": "one-line ring-announcer call of the moment, ≤ 110 chars, hype and funny (empty if not trash talk)"}, "flagged": {"type": "boolean", "description": "ONLY for direct threats of violence, sexual content about minors, or doxxing — never for offensive language"}}},
        steps: [{ kind: 'llm', template: 'live.arena.judge_mic', operation: 'generate', output: 'json', prepare: 'live.arena.judge_mic', postprocess: 'live.arena.judge', params: { max_tokens: 240, temperature: 0.4, timeout_ms: 25000 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.moments.pick', name: 'Pick one moment of a VOD (a screenshot paste or a clip)', namespace: 'live',
        description: 'The prompt Live used to render (ai-moments-job.js), now a versioned template: timeline, transcript, sounds, clip and chat signals in; one moment out.',
        input_schema: TEXT_OUT({
            title: STR(200), flavor: { enum: ['paste', 'clip'] },
            timeline: { type: 'array', maxItems: 400, items: { type: 'object', required: ['t', 'text'], additionalProperties: false, properties: { t: { type: 'number', minimum: 0 }, text: STR(2000) } } },
            transcript: { type: 'array', maxItems: 1500, items: { type: 'object', required: ['t', 'text'], additionalProperties: false, properties: { t: { type: 'number', minimum: 0 }, text: STR(2000) } } },
            sounds: { type: 'array', maxItems: 500, items: { type: 'object', required: ['t', 'label'], additionalProperties: false, properties: { t: { type: 'number', minimum: 0 }, label: STR(120) } } },
            clipped: { type: 'array', maxItems: 100, items: { type: 'number', minimum: 0 } },
            spikes: { type: 'array', maxItems: 100, items: { type: 'number', minimum: 0 } },
            avoid: { type: 'array', maxItems: 500, items: { type: 'number', minimum: 0 } },
        }, ['title']),
        output_schema: TEXT_OUT({ t: { type: 'integer', minimum: 0 }, title: STR(90), desc: STR(420) }, ['t', 'title', 'desc']),
        steps: [{ kind: 'llm', template: 'live.moments.pick', operation: 'generate', output: 'json', prepare: 'live.moments.pick', postprocess: 'live.moments.pick', params: { max_tokens: 300 } }],
        cache_mode: 'none',
    },
    {
        key: 'live.stream.recap', name: 'After-show report for a finished stream', namespace: 'live',
        input_schema: TEXT_OUT({ facts: { type: 'object' }, sources: SOURCES(0, 50) }, ['facts']),
        output_schema: TEXT_OUT({ headline: STR(90), summary: STR(500), moment: STR(200), tags: { type: 'array', items: STR(200), maxItems: 4 }, grade: { enum: ['S', 'A', 'B', 'C'] } }, ['headline', 'summary', 'moment', 'tags', 'grade']),
        steps: [{ kind: 'llm', template: 'live.stream.recap', operation: 'generate', output: 'json', postprocess: 'live.stream.recap', params: { max_tokens: 500, temperature: 0.8, timeout_ms: 40000 } }],
        cache_mode: 'private',
    },
    {
        key: 'live.media.transcribe', name: 'Speech-to-text for a VOD, clip or audio file', namespace: 'live',
        description: 'whisper.cpp on this host (Live\'s transcribe.js), media fetched only from allow-listed OpenVibe hosts.',
        input_schema: TEXT_OUT({ media: MEDIA_REF, media_url: STR(2048), language: LANG, seconds: { type: 'integer', minimum: 0, maximum: 36000 }, offset_sec: { type: 'number', minimum: 0 } }, []),
        output_schema: TEXT_OUT({ text: { type: 'string' }, language: STR(8), segments: { type: 'array', items: { type: 'object', required: ['start', 'end', 'text'], properties: { start: { type: 'number' }, end: { type: 'number' }, text: { type: 'string' } } } } }, ['text', 'segments']),
        steps: [{ kind: 'transcribe', route: 'live.stt' }],
        cache_mode: 'private',
    },
    {
        key: 'network.site_copy', name: 'Footer copy for the shared network chrome', namespace: 'network',
        description: 'Reverses the dependency: OpenVibe.Network used to call Live\'s /internal/ai/site-copy for this.',
        input_schema: TEXT_OUT({
            sites: { type: 'array', minItems: 1, maxItems: 24, items: { type: 'object', required: ['id'], properties: { id: STR(40), name: STR(60), what: STR(400), popular: { type: 'array', items: STR(200), maxItems: 8 } } } },
            links: { type: 'array', maxItems: 80, items: { type: 'object', required: ['id'], properties: { id: STR(60), name: STR(60), about: STR(120) } } },
        }, ['sites']),
        output_schema: TEXT_OUT({ sites: { type: 'array', items: { type: 'object', required: ['id', 'blurb', 'picks'], properties: { id: STR(40), blurb: STR(300), picks: { type: 'array', items: STR(60), maxItems: 4 } } } } }, ['sites']),
        steps: [{ kind: 'llm', template: 'network.site_copy', operation: 'generate', output: 'json', prepare: 'network.site_copy', postprocess: 'network.site_copy', params: { max_tokens: 2200, temperature: 0.7, timeout_ms: 60000 } }],
        cache_mode: 'service', cache_ttl_sec: 12 * 3600,
    },
];

// ── Passthrough workflows (prompt still rendered by Live) ──
const PASSTHROUGH_INPUT = {
    type: 'object', additionalProperties: false,
    properties: {
        role: { enum: ROLES },
        kind: STR(64),
        source: STR(64),
        system: { anyOf: [STR(400000), { type: 'array', maxItems: 12, items: { type: 'object', required: ['text'], additionalProperties: false, properties: { text: STR(400000), cache: { type: 'boolean' } } } }] },
        messages: { type: 'array', maxItems: 200, items: { type: 'object', required: ['role', 'content'], properties: { role: { enum: ['user', 'assistant'] }, content: {} } } },
        user: STR(800000),
        image: IMAGE,
        json: { type: 'object', required: ['schema'], properties: { name: STR(64), schema: { type: 'object' }, strict: { type: 'boolean' }, description: STR(500) } },
        max_tokens: { type: 'integer', minimum: 1, maximum: 16000 },
        temperature: { type: ['number', 'null'], minimum: 0, maximum: 2 },
        timeout_ms: { type: 'integer', minimum: 1000, maximum: 120000 },
        cache_key: STR(128),
    },
    anyOf: [{ required: ['user'] }, { required: ['messages'] }],
};
const PASSTHROUGH_OUTPUT = { type: 'object', required: ['text', 'json'], properties: { text: { type: 'string' }, json: { type: ['object', 'array', 'null'] } } };

const PASSTHROUGH = [
    ['live.complete', 'Any other Live completion', 'Fallback for a Live llm.complete() kind without its own workflow yet.'],
    ['live.viewers.line', 'AI viewers: single line', 'viewers/budget.js generate() — ai_viewers (chat reply).'],
    ['live.chat.insight', 'Chat insights and session overviews', 'chat-ai.js and chat-ai-routes.js — chat_global, chat_user, chat_relay, chat_anon, combined_overview, session_titles.'],
    ['live.arena.scene', 'Arena: scene description', 'arena-service.js — arena_scene.'],
    ['live.arena.judge', 'Arena: beef and mic judging', 'arena/listener.js — arena_beef_judge, arena_mic_judge.'],
    ['live.status_check', 'Provider probe', 'ai-analysis.testStatus / llm.testProvider — status_check.'],
];

const passthrough = PASSTHROUGH.map(([key, name, description]) => ({
    key, name, namespace: 'live', description: `${description} Prompt rendered by Live (passthrough); the run records only its hash.`,
    input_schema: PASSTHROUGH_INPUT, output_schema: PASSTHROUGH_OUTPUT,
    steps: [{ kind: 'passthrough', route_prefix: 'live' }],
    cache_mode: 'none',
    metadata: { passthrough: true },
}));

/** Live llm.complete() `kind` -> workflow key (the Live client uses the same table). */
const KIND_TO_WORKFLOW = {
    ai_viewers_director: 'live.viewers.plan', ai_viewers_reply: 'live.viewers.reply', ai_viewers: 'live.viewers.line', ai_viewers_fold: 'live.viewers.fold',
    chat_global: 'live.chat.insight', chat_user: 'live.chat.insight', chat_relay: 'live.chat.insight', chat_anon: 'live.chat.insight', combined_overview: 'live.chat.insight', session_titles: 'live.chat.insight',
    moment_vod_rank: 'live.moments.rank', moment_pick: 'live.moments.pick', auto_clip_confirm: 'live.clips.confirm', hero_slogans: 'live.hero.slogans', easter_egg: 'live.easter_egg', home_star: 'live.home.star',
    arena_persona: 'live.arena.persona', arena_quotes: 'live.arena.quotes', arena_scene: 'live.arena.scene', arena_beef_judge: 'live.arena.judge', arena_mic_judge: 'live.arena.judge', arena_headline: 'live.arena.headline',
    status_check: 'live.status_check',
};

module.exports = { templates, workflows: [...structured, ...passthrough], KIND_TO_WORKFLOW, ROLES, PASSTHROUGH_INPUT, PASSTHROUGH_OUTPUT };
